### ISSUE TITLE
the implementation of pitch and yaw 

### ISSUE THREAD

**Issue by yyakult** [Samsung/360tools#4]
Hi,
I have a question about the two parameters **pitch** and **yaw**. To my point of view, applying these two parameters should result in a rotated projection with certain pitch and yaw angle.
Therefore, when I use the command line bellow to generate a cubemap projection with a yaw angle (180 degree) and a default pitch angle (90 degree), it seems that your code does not work.
```
./360tools_conv -i ERP.yuv -o ERP2CMP.yuv -w 3840 -h 1920 -f 3 -l 3840 -m 2880 -n 1 -x 1 -y 1 -p 90 -t 180
```
Or maybe I have the wrong comprehension on these two parameters. 
Thank you very much!

Regards,
Lan

**Comment by kpchoi** [comment]
Hi,
pitch and yaw is for only TSP projection. it doesn't effect to cube map projection.
you can check help meesage from -h option.
I'm not sure that cube map also requires the functionality.

**Comment by yyakult** [comment]
Hi,
Thank you for your reply. It seems that I misunderstand the usage of these two parameters.
So, these two parameters only works for TSP projection, and the aim is to change the primary viewport center. Is that right?

Regards,
Lan

**Comment by kpchoi** [comment]
Dear Lan,
You're right. it's for viewport chaning.

Regards.
KP

**Comment by yyakult** [comment]
Thank you very much!
