### ISSUE TITLE
the cubemap projection

### ISSUE THREAD

**Issue by yyakult** [Samsung/360tools#5]
Hi,
I use the following command line to generate a cubemap projection.
```
./360tools_conv -i ERP.yuv -o CMP.yuv -w 3840 -h 1920 -f 3 -l 3840 -m 2880 -n 1
```
The layout of CMP should be like:
```
     +--------+--------+--------+--------+ 1
     |        |        |        |        |
     |        |   1    |        |        |
     |        |        |        |        |
     +--------+--------+--------+--------+ H/3
     |        |        |        |        |
     |   2    |   3    |    4   |   5    |
     |        |        |        |        |
     +--------+--------+--------+--------+ H/3*2
     |        |        |        |        |
     |        |   6    |        |        |
     |        |        |        |        |
     +--------+--------+--------+--------+
     1       W/4     W/2     W/4*3
```
For my input YUV file, the width and height of each square of CMP should be 960. Therefore, the value of output Y(1:960, 1:960) should be 0. But this square indeed has non-zero value on the edge of the square:
![](https://github.com/yyakult/Image-Distortion-Measurement/blob/master/untitled.jpg?raw=true)

The same problem occurs in other square:
![](https://github.com/yyakult/Image-Distortion-Measurement/blob/master/untitled2.jpg?raw=true)

Why did this happened?

Regards,
Lan

**Comment by vladZakharchenko** [comment]
That is a good question.
If you try using this cubemap for, let's say, OpenGl there will be noticeable stitches between adjacent faces due to interpolation in texture rendering process, thus some extra padding added to increase quality. That is what you see on those patches.

**Comment by yyakult** [comment]
Oh, I know. Thank you! 

Regards,
Lan
