### ISSUE TITLE
how to calculate s-psnr

### ISSUE THREAD

**Issue by CodingHang** [Samsung/360tools#7]
how to use the file(sphere_655362.txt)?
why the number of point is 655362?

**Comment by vladZakharchenko** [comment]
Hi, lonelylonelylonely.
You can use spherical coordinates file with -s key in metrics binary file.
File sphere_655362.txt contains long/lat coordinates of the "evenly distributed" points on the sphere surface. 
The nuber of points is following Original paper - "[A Framework to Evaluate Omnidirectional Video Coding Schemes](http://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=7328056)" by Matt Yu, Haricharan Lakshman and Bernd Girod
