### ISSUE TITLE
The result of metric is -nan

### ISSUE THREAD

**Issue by YsSue** [Samsung/360tools#8]
Hello, I use this code on Linux, make and run:
./360tools_metric -w 4096 -h 2048 -f 1 -o ../Video02-150Frame/video02-Re.jpg -q 1 -l 4096-m 2048 -t 1 -r ../Video02-150Frame/video02-3MB-264.jpg -n 1 -x 1
then the result is:
QM_ID=1	 -nan	 -nan	 -nan
both distorted image and reference image are same width and height, same Equirectangular projection, and I don't know what's wrong.

**Comment by kpchoi** [comment]
Hi,
360tools supports YUV 4:2:0 format.
For testing quality by using 360tools_metric, you need to change the JPG file to YUV format, and set -o and -r parameter with YUV file instead of JPG file.
